name: GitHub - Activity - Readme
description: (Reborn) Updates README with the recent GitHub activity of a user
author: BrandgrandRealMe

inputs:
  USERNAME:
    description: 'Your GitHub username'
    default: ${{ github.repository_owner }}

branding:
  color: yellow
  icon: activity

runs:
  using: node12
  main: dist/index.js
